name: quizsquare
description: A Flutter Quiz App.

version: 1.0.0+2

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  http: ^1.3.0
  flutter_custom_clippers: ^2.1.0
  html_unescape: ^2.0.0
  auto_size_text: ^3.0.0
  circular_countdown_timer: ^0.2.4
  fluttertoast: ^8.2.12
  syncfusion_flutter_gauges: ^28.2.12
  double_back_to_close_app: ^2.1.0
  loading_animations: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/

module:
  androidX: true # Add this line.
